import {build} from 'esbuild';
import {mkdir,copyFile,rm,cp} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {resolve,dirname} from 'node:path';
const root=dirname(fileURLToPath(import.meta.url)),out=resolve(root,'dist');
await rm(out,{recursive:true,force:true});
await mkdir(out,{recursive:true});
await build({entryPoints:[root+'/src/mobile-bootstrap.js'],bundle:true,minify:true,format:'esm',outfile:out+'/app.js'});
await build({entryPoints:[root+'/src/legacy/legacy-app.js'],bundle:true,minify:true,format:'esm',outfile:out+'/legacy-app.js'});
await build({entryPoints:[root+'/src/components/loading-3d.js'],bundle:true,minify:true,format:'esm',outfile:out+'/loading-3d.js'});
await copyFile(root+'/src/legacy/legacy.html',out+'/legacy.html');
await copyFile(root+'/src/index.html',out+'/index.html');
for(const f of ['style.css','redesign.css','child.css','world.css','mobile.css'])await copyFile(root+'/src/styles/'+f,out+'/'+f);
await copyFile(root+'/src/pages/dinosaur-world/trex/knowledge.css',out+'/knowledge.css');
await copyFile(root+'/src/pages/dinosaur-world/species-knowledge.css',out+'/species-knowledge.css');
await copyFile(root+'/src/pages/dinosaur-world/stego/stego-exploration.css',out+'/stego-exploration.css');
await copyFile(root+'/src/pages/ocean-world/ocean-knowledge.css',out+'/ocean-knowledge.css');
await copyFile(root+'/src/components/loading-3d.css',out+'/loading-3d.css');
await cp(root+'/assets',out+'/assets',{recursive:true,filter:p=>!(/\.(zip|rar)$/i.test(p))});
await cp(root+'/video',out+'/video',{recursive:true});
console.log('Built '+out);

