import {buildActionLessons} from '../core/action-lessons.js';
import {catalog,ids,matchesWord} from '../pages/dinosaur-world/catalog.js';
import {createHabitat} from './legacy-scene.js';

const $=id=>document.getElementById(id),esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let saved={};try{saved=JSON.parse(localStorage.getItem('dino-island-progress')||'{}');if(!saved||typeof saved!=='object'||Array.isArray(saved))saved={};}catch{}
const originalLessons=Object.fromEntries(ids.map(id=>[id,catalog[id].lessons.slice()]));
let selected='trex',screen='map',lessonIndex=0,habitat,loading=false,request=0,recognition=null,quizAnswer=null;
const lesson=()=>catalog[selected].lessons[lessonIndex];
function progress(){const done=catalog[selected].lessons.every(l=>saved[selected+':'+(l.actionKey||l.word)]);$('completion').hidden=!done;$('completion').textContent='✓ Đã hoàn thành bộ từ của '+catalog[selected].name+'. Bạn có thể ôn lại hoặc chọn loài khác.';const count=ids.reduce((sum,id)=>sum+catalog[id].lessons.filter(l=>saved[id+':'+(l.actionKey||l.word)]).length,0);$('progress').textContent=count+' từ đã luyện';if(screen==='learn')$('lesson-count').textContent=catalog[selected].lessons.filter(l=>saved[selected+':'+(l.actionKey||l.word)]).length+'/'+catalog[selected].lessons.length;}
function mark(){saved[selected+':'+(lesson().actionKey||lesson().word)]=true;try{localStorage.setItem('dino-island-progress',JSON.stringify(saved));}catch{}progress();}
function cancelVoice(){recognition?.abort();recognition=null;$('mic').textContent='🎙 Bấm để nói';window.speechSynthesis?.cancel();}
function speak(text){if(!$('sound').checked)return;if(!('speechSynthesis'in window)){$('feedback').textContent='Trình duyệt chưa hỗ trợ đọc mẫu. Bạn có thể đọc câu và xem động tác.';return;}window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.82;const voice=window.speechSynthesis.getVoices().find(v=>v.lang==='en-US')||window.speechSynthesis.getVoices().find(v=>v.lang.startsWith('en'));if(voice)u.voice=voice;window.speechSynthesis.speak(u);}
function route(next){screen=next;document.body.dataset.screen=next;$('map-screen').hidden=next!=='map';$('experience').hidden=next==='map';$('intro-panel').hidden=next!=='intro';$('learn-panel').hidden=next!=='learn';$('back').hidden=next==='map';habitat?.setActive(next==='learn');if(next!=='map')pauseCards();else updateCards();}
function map(){location.href='index.html#map';return;request++;loading=false;cancelVoice();habitat?.stop();route('map');location.hash='map';}
const value=a=>a.display|| (typeof a.value==='object'?JSON.stringify(a.value):String(a.value))+(a.unit?' '+a.unit:'');
async function openSpecies(id){if(id==='trex'){location.href='index.html#intro/trex';return;}const ticket=++request;cancelVoice();selected=id;loading=true;route('intro');location.hash='intro/'+id;const c=catalog[id];$('hero-image').src='assets/heroes/'+id+'.png';$('hero-image').alt=c.name+' trong môi trường phục dựng';$('stage-species').textContent=c.name;$('species-position').textContent=String(ids.indexOf(id)+1).padStart(2,'0')+' / 06';$('species-name').textContent=c.name;$('scientific').textContent=c.info.scientificName;$('summary').textContent=c.info.summary;$('habitat').textContent=c.region;$('pose-status').textContent='Meet your dinosaur';$('learn').textContent='Tìm hiểu '+c.name+' →';$('learn').disabled=true;$('facts').innerHTML=c.info.attributes.filter(a=>['length','length_m','body_length','mass','mass_kg','body_mass','diet','period','range'].includes(a.key)).slice(0,5).map(a=>`<div><dt>${esc(a.label)}</dt><dd>${esc(value(a))}</dd></div>`).join('');$('load-status').hidden=false;$('load-status').textContent='Đang đến '+c.region.toLowerCase()+'…';
 try{habitat??=createHabitat($('stage'));await habitat.load(id);if(ticket!==request)return;catalog[id].lessons=buildActionLessons(c.name,habitat.definitions,originalLessons[id]);$('load-status').hidden=true;loading=false;$('learn').disabled=false;}catch(e){if(ticket!==request)return;loading=false;$('load-status').textContent='Chưa tải được model. Bấm ↻ để thử lại.';console.error(e);}
}
function showLesson(i){cancelVoice();lessonIndex=i;habitat.stop();$('quiz').hidden=true;quizAnswer=null;const l=lesson();$('word').textContent=l.word;$('selected-action').textContent=l.actionLabel||l.meaning;$('meaning').textContent=l.meaning;$('example').textContent=l.example;$('translation').textContent=l.translation;$('translation').hidden=true;$('translate').textContent='Hiện nghĩa';$('feedback').textContent='Nghe mẫu, rồi thử nói “'+l.word.toLowerCase()+'”.';document.querySelectorAll('[data-lesson]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.lesson)===i)));progress();}
function learn(){if(loading)return;cancelVoice();route('learn');location.hash='learn/'+selected;$('pose-status').textContent='Nói tiếng Anh để tạo chuyển động';$('action-tabs').innerHTML=catalog[selected].lessons.map((l,i)=>`<button data-lesson="${i}" aria-pressed="false">${esc(l.word)}<small>${esc(l.actionLabel||l.meaning)}</small></button>`).join('');$('action-tabs').querySelectorAll('button').forEach(b=>b.onclick=()=>showLesson(Number(b.dataset.lesson)));showLesson(0);requestAnimationFrame(()=>requestAnimationFrame(()=>habitat.fit(true)));}
function perform(){if(!habitat?.play(lesson().clip)){$('feedback').textContent='Chưa có động tác này trong model.';return;}$('feedback').textContent=lesson().word+' — '+lesson().meaning+'. Hãy quan sát chuyển động.';}
const normalize=text=>text.toLowerCase().replace(/[^a-z\s]/g,' ').replace(/\s+/g,' ').trim();
function recognized(text){if(screen!=='learn')return;const ok=$('sentence-mode').checked?normalize(text)===normalize(lesson().example):matchesWord(text,lesson().word);if(ok){mark();perform();$('feedback').textContent='✓ Đã nhận được “'+lesson().word+'”. Xem người bạn của bạn chuyển động!';}else $('feedback').textContent='Nghe được: “'+text+'”. Thử lại từ “'+lesson().word+'” nhé.';}
function mic(){if(recognition){cancelVoice();return;}const Speech=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Speech){$('feedback').textContent='Trình duyệt này chưa hỗ trợ nhận giọng nói. Dùng Nghe từ và Xem động tác, hoặc thử Chrome.';return;}window.speechSynthesis?.cancel();const r=new Speech();recognition=r;r.lang='en-US';r.interimResults=false;r.maxAlternatives=3;const id=selected,index=lessonIndex;r.onstart=()=>{$('mic').textContent='■ Dừng nghe';$('feedback').textContent='Đang nghe… nói “'+($('sentence-mode').checked?lesson().example:lesson().word)+'”.';};r.onresult=e=>{if(screen!=='learn'||id!==selected||index!==lessonIndex)return;const alternatives=Array.from(e.results[0]).map(a=>a.transcript);recognized(alternatives.find(t=>($('sentence-mode').checked?normalize(t)===normalize(lesson().example):matchesWord(t,lesson().word)))||alternatives[0]);};r.onerror=e=>{$('feedback').textContent=e.error==='not-allowed'?'Micro chưa được cho phép. Bạn có thể bật quyền micro hoặc dùng Xem động tác.':e.error==='no-speech'?'Chưa nghe thấy tiếng nói. Bấm micro để thử lại.':'Chưa nhận được giọng nói. Kiểm tra kết nối hoặc dùng Xem động tác.';};r.onend=()=>{if(recognition===r)recognition=null;$('mic').textContent='🎙 Bấm để nói';};try{r.start();}catch{recognition=null;$('feedback').textContent='Không mở được micro. Bạn vẫn có thể xem động tác.';}}
function info(){const c=catalog[selected],s=c.info;$('info-content').innerHTML=`<span class="eyebrow">HỒ SƠ LOÀI</span><h2>${esc(c.name)}</h2><i>${esc(s.scientificName)}</i><p>${esc(s.summary)}</p><p class="small-note">${esc(s.identityNote)}</p><h3>Phân loại</h3><p>${s.taxonomy.map(esc).join(' → ')}</p><dl>${s.attributes.map(a=>`<div><dt>${esc(a.label)}</dt><dd>${esc(value(a))}</dd></div>`).join('')}</dl><h3>Nguồn tham khảo</h3>${s.sources.filter(s=>/^https?:\/\//.test(s.url)).map(s=>`<p><a href="${esc(s.url)}" target="_blank" rel="noopener noreferrer">${esc(s.title)}</a></p>`).join('')}`;cancelVoice();habitat.stop();$('info-dialog').showModal();}
$('island').innerHTML='<img class="island-art" src="assets/prehistoric-island.png" alt="">'+ids.map(id=>{const c=catalog[id];return `<button class="map-pin ${id}" style="--x:${c.pos[0]}%;--y:${c.pos[1]}%" data-species="${id}" aria-label="Khám phá ${c.name}"><img src="assets/heroes/${id}.png" alt=""><b>${c.name}</b><span>KHÁM PHÁ →</span></button>`;}).join('');
$('cards').innerHTML=ids.map((id,i)=>`<button class="creature-card" data-species="${id}"><div><img src="assets/${id}.png" alt=""><video muted playsinline loop preload="none" data-id="${id}" poster="assets/${id}.png"></video><span class="card-number">0${i+1}</span><span class="play-dot">▶</span></div><b>${catalog[id].name}</b><small>${catalog[id].region}</small></button>`).join('');
const visible=new Set(),reduced=matchMedia('(prefers-reduced-motion: reduce)');function pauseCards(){document.querySelectorAll('#cards video').forEach(v=>v.pause());}function updateCards(){pauseCards();if(screen!=='map'||document.hidden||reduced.matches)return;for(const v of [...visible].slice(0,3)){v.src||= 'assets/'+v.dataset.id+'-1.mp4';v.playbackRate=1.25;v.play().catch(()=>{});}}
const observer=new IntersectionObserver(entries=>{for(const e of entries){if(e.isIntersecting&&e.intersectionRatio>=.5)visible.add(e.target);else visible.delete(e.target);}updateCards();},{threshold:.5});document.querySelectorAll('#cards video').forEach(v=>observer.observe(v));reduced.addEventListener('change',updateCards);document.addEventListener('visibilitychange',()=>{if(document.hidden)cancelVoice();updateCards();});document.querySelectorAll('[data-species]').forEach(b=>b.onclick=()=>openSpecies(b.dataset.species));
$('back').onclick=()=>screen==='learn'?openSpecies(selected):map();$('learn').onclick=learn;$('say-name').onclick=()=>speak(catalog[selected].info.scientificName);$('hear-word').onclick=()=>speak(lesson().word);$('hear-sentence').onclick=()=>speak(lesson().example);$('translate').onclick=()=>{$('translation').hidden=!$('translation').hidden;$('translate').textContent=$('translation').hidden?'Hiện nghĩa':'Ẩn nghĩa';};$('perform').onclick=perform;$('mic').onclick=mic;$('info').onclick=info;$('reset-camera').onclick=()=>habitat?.fit();$('replay-intro').onclick=()=>habitat?.fit(true);$('previous-species').onclick=()=>openSpecies(ids[(ids.indexOf(selected)+ids.length-1)%ids.length]);$('next-species').onclick=()=>openSpecies(ids[(ids.indexOf(selected)+1)%ids.length]);
$('next-lesson').onclick=()=>showLesson((lessonIndex+1)%catalog[selected].lessons.length);$('quiz-replay').onclick=()=>{if(quizAnswer!==null)speak(catalog[selected].lessons[quizAnswer].word);};
$('challenge').onclick=()=>{if(!$('sound').checked){$('feedback').textContent='Bật đọc mẫu trong Cài đặt để làm bài nghe.';return;}quizAnswer=Math.floor(Math.random()*catalog[selected].lessons.length);$('quiz').hidden=false;$('quiz-prompt').textContent='Nghe và chọn từ bạn vừa nghe.';$('quiz-options').innerHTML=catalog[selected].lessons.map((l,i)=>`<button data-answer="${i}">${esc(l.word)}</button>`).join('');speak(catalog[selected].lessons[quizAnswer].word);$('quiz-options').querySelectorAll('button').forEach(b=>b.onclick=()=>{if(Number(b.dataset.answer)===quizAnswer){const chosen=quizAnswer;showLesson(chosen);mark();perform();$('feedback').textContent='✓ Đúng rồi! '+lesson().word;}else $('quiz-prompt').textContent='Chưa đúng, thử một từ khác nhé.';});};
$('settings').onclick=()=>{cancelVoice();$('settings-dialog').showModal();};document.querySelectorAll('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());$('reset-progress').onclick=()=>{if(confirm('Xóa tiến trình học trên trình duyệt này?')){saved={};try{localStorage.removeItem('dino-island-progress');}catch{}progress();}};
function fromHash(){const [page,id]=location.hash.slice(1).split('/');if(catalog[id]&&['intro','learn'].includes(page)){openSpecies(id).then(()=>{if(page==='learn'&&!loading&&screen!=='map')learn();});}else map();}window.addEventListener('popstate',()=>{if(location.hash!==('#'+screen+(screen==='map'?'':'/'+selected)))fromHash();});document.querySelector('.brand').onclick=e=>{e.preventDefault();map();};progress();route('map');if(location.hash&&location.hash!=='#map')fromHash();
window.dinoGame={get screen(){return screen;},get selected(){return selected;},get state(){return habitat?.state;},get lessons(){return catalog[selected].lessons;}};
