import {createMobileUI,createModelLoading} from './mobile-ui.js';
import {catalog,ids as dinosaurIds} from './catalog.js';
import {marine,hiddenMarineIds,visibleMarineIds} from './marine.js';
import {oceanTopicButtons,oceanContent,createOceanKnowledge} from './ocean-knowledge.js';
import {speciesKnowledge} from './species-knowledge-data.js';
import {speciesTopicButtons,createSpeciesKnowledge} from './species-knowledge-view.js';
import {createHabitat} from './scene.js';
import {topicButtons,topics,createKnowledgeView} from './knowledge.js';
import {previewMarkup,createActionPreviews} from './action-previews.js';
const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const seaIds=visibleMarineIds,all={...catalog,...marine};let selected='trex',world='dinosaurs',screen='home',habitat,ticket=0,loading=false,currentAction='',defs={};
const previews=createActionPreviews(),knowledge=createKnowledgeView({speak}),oceanKnowledge=createOceanKnowledge({speak}),speciesView=createSpeciesKnowledge({speak});
const hasTopic=(id,key)=>!!(speciesKnowledge[id]?.topics[key]||(id==='trex'&&topics[key])||oceanContent[id]?.[key]);
function speak(text,lang='vi-VN'){if(!window.speechSynthesis)return;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang=lang;speechSynthesis.speak(u);}
const group=id=>marine[id]?'ocean':'dinosaurs',list=()=>world==='ocean'?seaIds:dinosaurIds;
const portrait=id=>'/assets/portraits/'+id+'.webp';
const environment=id=>id==='trex'?'/assets/knowledge/trex/habitat.png':'/assets/worlds/'+(marine[id]?.env||({mosa:'deep',ptero:'cliffs'}[id]||'forest'))+'.png';
function imageMarkup(id){return `<img src="${portrait(id)}" alt="${esc(all[id].name)}" onerror="this.onerror=null;this.src='/assets/${marine[id]?'knowledge/trex/icon-range.png':id+'.png'}'">`;}
function notify(text){$('notice').textContent=text;clearTimeout(notify.timer);notify.timer=setTimeout(()=>$('notice').textContent='',2400);}
const modelLoading=createModelLoading($('load-status'));
createMobileUI({notify});
function route(next){$('notice').textContent='';screen=next;document.body.dataset.screen=next;document.body.dataset.world=world;$('home-screen').hidden=next!=='home';$('map-screen').hidden=next!=='map';$('experience').hidden=['home','map'].includes(next);$('action-tray').hidden=next!=='learn';$('topic-hub').hidden=!['intro','topic'].includes(next);$('knowledge-view').hidden=next!=='topic';$('learn-panel').hidden=true;$('back').hidden=next==='home';$('say-name').hidden=!['intro','topic'].includes(next);habitat?.setActive(['intro','learn'].includes(next));previews.setActive(['home','intro','learn','topic','map'].includes(next));previews.refresh();}
function navigate(path,replace=false){history[replace?'replaceState':'pushState']({},'',path);readRoute();}
function showMap(){ticket++;route('map');$('island').innerHTML=`<img class="island-art" src="/assets/${world==='ocean'?'worlds/ocean.png':'prehistoric-island.png'}" alt="">`+list().map((id,i)=>{const pos=world==='ocean'?({seal:[12,28],squid:[30,44],loggerhead:[54,32],tuna:[77,33],slug:[50,51],shark:[85,57],fish:[38,51],amplectobelua:[66,64]})[id]:catalog[id].pos;return `<button class="map-pin ${id}" style="--x:${pos[0]}%;--y:${pos[1]}%;--px:${pos[0]/100};--py:${pos[1]/100}" data-species="${id}" aria-label="${esc(all[id].name)}"><img src="/assets/${marine[id]?'map-portraits/'+id+'.png':'heroes/'+id+'.png'}" alt="${esc(all[id].name)}"></button>`;}).join('');$('cards').innerHTML=list().map(id=>`<button class="creature-card" data-species="${id}" aria-label="${esc(all[id].name)}">${marine[id]||['deino','brachio'].includes(id)?previewMarkup(id,['isopod','shark'].includes(id)?'drift':'clip0'):'<video muted autoplay loop playsinline preload="metadata" poster="/assets/'+id+'.png" src="/assets/'+id+'-1.mp4"></video>'}</button>`).join('');previews.refresh();$('map-screen').querySelectorAll('button[data-species]').forEach(b=>b.onclick=()=>navigate('/animal/'+b.dataset.species));layoutMap();updateCards();$('world-title').textContent=world==='ocean'?'OCEAN WORLD':'DINOSAUR WORLD';}
async function open(id,action,topic){const request=++ticket;selected=id;world=group(id);document.body.dataset.species=id;document.body.dataset.marine=String(!!marine[id]);loading=true;route('intro');$('stage').style.opacity='0';defs={};$('experience').style.setProperty('--environment',`url("${environment(id)}")`);$('hero-image').hidden=!!marine[id];if(!marine[id])$('hero-image').src='/assets/heroes/'+id+'.png';$('hero-backdrop').style.backgroundImage=`url("${environment(id)}")`;modelLoading.begin(id,!!marine[id]);$('topic-hub').innerHTML=`<button class="action-orb" data-enter-3d disabled aria-label="Xem animation">${imageMarkup(id)}<span class="orb-play">▶</span></button>`+(speciesKnowledge[id]?speciesTopicButtons(id):marine[id]?oceanTopicButtons():topicButtons());$('topic-hub').querySelector('[data-enter-3d]').onclick=()=>navigate('/animal/'+id+'/actions/'+Object.keys(defs)[0]);document.querySelectorAll('#topic-hub button[data-topic]').forEach(b=>{b.setAttribute('aria-disabled',String(!hasTopic(id,b.dataset.topic)));b.onclick=()=>hasTopic(id,b.dataset.topic)?navigate('/animal/'+id+'/topics/'+b.dataset.topic):notify('Mục này chưa có nội dung');});
try{habitat??=createHabitat($('stage'));await habitat.load(id);if(ticket!==request)return;defs=habitat.definitions;loading=false;$('stage').style.opacity='1';modelLoading.end();document.querySelector('[data-enter-3d]').innerHTML=previewMarkup(id,Object.keys(defs)[0])+'<span class="orb-play">▶</span>';document.querySelector('[data-enter-3d]').disabled=false;$('action-picker').innerHTML=Object.entries(defs).map(([key,spec])=>`<button class="action-orb" data-action="${esc(key)}" aria-label="${esc(spec[1])}" title="${esc(spec[1])}">${previewMarkup(id,key)}<span class="orb-play">▶</span><span class="action-label">${esc(spec[1])}</span></button>`).join('');$('action-picker').querySelectorAll('button').forEach(b=>b.onclick=()=>navigate('/animal/'+id+'/actions/'+encodeURIComponent(b.dataset.action)));previews.refresh();habitat.setActive(true);habitat.play(Object.keys(defs)[0]);habitat.fit(true);if(topic&&hasTopic(id,topic)){route('topic');if(speciesKnowledge[id])speciesView.show(id,topic);else if(marine[id])oceanKnowledge.show(id,topic);else{$('knowledge-view').dataset.owner='dinosaur';knowledge.show(topic);}}else if(action){showAction(action);}updateTray();}catch(e){if(ticket!==request)return;loading=false;modelLoading.fail(()=>open(id,action,topic));console.error(e);}}
function showAction(key){if(!defs[key])key=Object.keys(defs)[0];currentAction=key;route('learn');habitat.play(key);habitat.fit(true);document.querySelectorAll('[data-action]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.action===key)));updateTray();}
function readRoute(){ $('load-status').hidden=true; window.speechSynthesis?.cancel();const p=decodeURIComponent(location.pathname).split('/').filter(Boolean);if(!p.length){ticket++;route('home');return;}if(p[0]==='world'&&['dinosaurs','ocean'].includes(p[1])){world=p[1];showMap();return;}if(p[0]==='animal'&&hiddenMarineIds.has(p[1])){navigate('/world/ocean',true);return;}if(p[0]==='animal'&&all[p[1]]){if(p[1]===selected&&!loading&&habitat&&Object.keys(defs).length&&p[2]==='actions'){showAction(p[3]);return;}open(p[1],p[2]==='actions'?p[3]:null,p[2]==='topics'?p[3]:null);return;}navigate('/',true);}
$('home-screen').innerHTML='<img class="home-art" src="/assets/worlds/home.png" alt="Bản đồ thế giới động vật">'+[{id:'dinosaurs',name:'THẾ GIỚI CỔ ĐẠI',x:23,y:36,art:'/assets/heroes/trex.png'},{id:'ocean',name:'ĐẠI DƯƠNG',x:80,y:46,art:'/assets/map-portraits/loggerhead.png'},{name:'ĐỒNG CỎ',x:13,y:64},{name:'RỪNG NHIỆT ĐỚI',x:46,y:44},{name:'NÚI & BẦU TRỜI',x:72,y:23},{name:'NÔNG TRẠI',x:42,y:81},{name:'VÙNG ĐẤT MỚI',x:88,y:82}].map(v=>`<button class="world-badge ${v.id?'available':'locked'}" style="left:${v.x}%;top:${v.y}%" ${v.id?'data-world="'+v.id+'"':'aria-disabled="true"'} aria-label="${v.name}"><span>${v.id?previewMarkup(v.id==='dinosaurs'?'trex':'loggerhead',v.id==='dinosaurs'?'roar':'clip0'):'🔒'}</span><b>${v.name}</b></button>`).join('');
$('home-screen').innerHTML='<div class="home-canvas">'+$('home-screen').innerHTML+'</div>';
$('home-screen').querySelectorAll('button[data-world]').forEach(b=>b.onclick=()=>navigate('/world/'+b.dataset.world));document.querySelectorAll('.world-badge.locked').forEach(b=>b.onclick=()=>notify('Vùng này sẽ được mở sau'));
$('back').onclick=()=>navigate(screen==='home'?'/':screen==='map'?'/':screen==='intro'?'/world/'+world:'/animal/'+selected);document.querySelector('.brand').onclick=e=>{e.preventDefault();navigate('/');};$('say-name').onclick=()=>screen==='topic'?(speciesKnowledge[selected]?speciesView:marine[selected]?oceanKnowledge:knowledge).narrate():speak(all[selected].name);$('reset-camera').onclick=()=>habitat?.fit(true);$('info').onclick=()=>notify(marine[selected]?'Model minh hoạ · animation gốc nếu có':'Chọn biểu tượng ở trang giới thiệu để xem thông tin');document.querySelectorAll('.close-dialog').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('previous-species').onclick=()=>navigate('/animal/'+list()[(list().indexOf(selected)+list().length-1)%list().length]);$('next-species').onclick=()=>navigate('/animal/'+list()[(list().indexOf(selected)+1)%list().length]);
function updateTray(){const e=$('action-picker');$('actions-prev').disabled=e.scrollLeft<=2;$('actions-next').disabled=e.scrollLeft+e.clientWidth>=e.scrollWidth-2;}
for(const [id,d]of [['actions-prev',-1],['actions-next',1]])$(id).onclick=()=>$('action-picker').scrollBy({left:d*300,behavior:'smooth'});$('action-picker').onscroll=updateTray;new ResizeObserver(updateTray).observe($('action-picker'));

function updateCards(){const e=$('cards');
 const real=[...e.querySelectorAll('.creature-card[data-species]')];let mystery=e.querySelector('.mystery-card');
 if(world==='dinosaurs'&&screen==='map'&&real.length){
  const gap=parseFloat(getComputedStyle(e).columnGap)||0;
  const used=real.reduce((n,b)=>n+b.getBoundingClientRect().width,0)+gap*(real.length-1);
  const spare=Math.floor(e.clientWidth-used-gap);
  if(spare>=44){if(!mystery){mystery=document.createElement('div');mystery.className='creature-card mystery-card';mystery.setAttribute('role','img');mystery.setAttribute('aria-label','Loài bí mật chưa mở');mystery.innerHTML='<span aria-hidden="true">?</span>';e.append(mystery);}mystery.style.flexBasis=spare+'px';}
  else mystery?.remove();
 }else mystery?.remove();
$('cards-prev').disabled=e.scrollLeft<=2;$('cards-next').disabled=e.scrollLeft+e.clientWidth>=e.scrollWidth-2;}
for(const [id,d]of [['cards-prev',-1],['cards-next',1]])$(id).onclick=()=>$('cards').scrollBy({left:d*Math.max(180,$('cards').clientWidth*.75),behavior:'smooth'});
$('cards').onscroll=updateCards;new ResizeObserver(updateCards).observe($('cards'));
// Keep marine pins and the painting in the same coordinate system, including on phones.
function layoutMap(){if(world!=='ocean'&&!matchMedia('(max-width:1024px)').matches){$('island').querySelectorAll('.map-pin').forEach(pin=>pin.style.removeProperty('top'));return;}const e=$('island'),art=e.querySelector('img.island-art');if(!art)return;const map=$('map-screen'),tray=document.querySelector('.catalog-tray');map.style.setProperty('--ocean-tray-space',(map.getBoundingClientRect().bottom-tray.getBoundingClientRect().top+12)+'px');const w=Math.max(e.clientWidth,map.clientHeight*1.777,matchMedia('(max-width:1024px)').matches?0:820),h=w/1.777;e.style.setProperty('--map-width',w+'px');e.style.setProperty('--map-height',h+'px');e.querySelectorAll('.map-pin').forEach(pin=>{const py=Number(pin.style.getPropertyValue('--py'));pin.style.top=Math.max(96,Math.min(h*py,tray.getBoundingClientRect().top-e.getBoundingClientRect().top-pin.offsetHeight/2-12))+'px';});}
new ResizeObserver(layoutMap).observe($('island'));new ResizeObserver(layoutMap).observe(document.querySelector('.catalog-tray'));
window.addEventListener('popstate',readRoute);if(location.hash){const [page,id,key]=location.hash.slice(1).split('/');history.replaceState({},'',all[id]?'/animal/'+id+(page==='learn'?'/actions/'+key:page==='topic'?'/topics/'+key:''):'/world/dinosaurs');}readRoute();window.dinoGame={get screen(){return screen},get selected(){return selected},get state(){return habitat?.state},get lessons(){return Object.entries(defs).map(([actionKey,s])=>({actionKey,word:s[1]}))},capture:async id=>{await habitat.load(id);return habitat.capturePortrait();}};
