import * as T from 'three';
import {createOceanProgress,OCEAN_GOALS} from './ocean-play-state.js';
export function createOceanPlay(scene,host,camera){
 const group=new T.Group();scene.add(group);const progress=createOceanProgress(),geometries=[],materials=[];
 const panel=document.createElement('div');panel.className='ocean-goals';panel.innerHTML='<span class="goal-step" aria-label="Vòng bong bóng">◯ ◯ ◯</span><span class="goal-step" aria-label="Thức ăn">🐚</span><span class="goal-step" aria-label="Khám phá"><svg width="22" height="22" viewBox="0 0 24 24" aria-hidden="true"><path fill="currentColor" d="M2 22V11a10 10 0 0 1 20 0v11h-5V11a5 5 0 0 0-10 0v11Z"/></svg></span><button class="ocean-replay" aria-label="Chơi lại" hidden>↻</button><span class="goal-direction" aria-hidden="true"></span>';host.append(panel);
 let audio=null,soundEnabled=true;const sound=document.createElement('button');sound.className='round ocean-sound';sound.setAttribute('aria-label','Tắt âm thanh trò chơi');sound.textContent='♪';host.append(sound);sound.onclick=()=>{soundEnabled=!soundEnabled;sound.setAttribute('aria-label',soundEnabled?'Tắt âm thanh trò chơi':'Bật âm thanh trò chơi');sound.setAttribute('aria-pressed',String(!soundEnabled));sound.textContent=soundEnabled?'♪':'♩';};
 function chime(){if(!soundEnabled)return;try{const C=window.AudioContext||window.webkitAudioContext;audio??=new C();audio.resume().catch(()=>{});for(let i=0;i<3;i++){const oscillator=audio.createOscillator(),gain=audio.createGain(),start=audio.currentTime+i*.10;oscillator.type='sine';oscillator.frequency.value=[523,659,784][i];gain.gain.setValueAtTime(0,start);gain.gain.linearRampToValueAtTime(.06,start+.015);gain.gain.exponentialRampToValueAtTime(.001,start+.22);oscillator.connect(gain).connect(audio.destination);oscillator.start(start);oscillator.stop(start+.25);}}catch{}}
 function mesh(geometry,color){geometries.push(geometry);const material=new T.MeshStandardMaterial({color,emissive:color,emissiveIntensity:.25,transparent:true,opacity:.85,roughness:.4});materials.push(material);return new T.Mesh(geometry,material);}
 const markers=OCEAN_GOALS.map((goal,i)=>{const g=new T.Group();g.position.set(goal.position[0],goal.position[1]+1.6,goal.position[2]);group.add(g);if(goal.kind==='ring'){const ring=mesh(new T.TorusGeometry(2.6,.1,8,40),0x8cf6ed);g.add(ring);for(let n=0;n<10;n++){const bubble=mesh(new T.SphereGeometry(.15,6,4),0xcbfff8);bubble.position.set(Math.cos(n*Math.PI/5)*2.6,Math.sin(n*Math.PI/5)*2.6,0);g.add(bubble);}}else if(goal.kind==='food'){const shell=mesh(new T.SphereGeometry(.55,10,6),0xffc47b);shell.scale.set(1,.45,.9);g.add(shell);const halo=mesh(new T.TorusGeometry(.9,.045,6,24),0xffe8ac);halo.rotation.x=Math.PI/2;g.add(halo);}else{const gem=mesh(new T.OctahedronGeometry(.75),0xffe495);g.add(gem);}return g;});
 const trail=[];for(let i=0;i<24;i++){const bubble=mesh(new T.SphereGeometry(.08+(i%3)*.025,5,4),0xb6ffff);bubble.visible=false;group.add(bubble);trail.push({mesh:bubble,life:0});}let spawn=0,time=0,celebrate=0;
 function updatePanel(position){const n=progress.index,steps=panel.querySelectorAll('.goal-step');steps[0].textContent=[0,1,2].map(i=>i<n?'●':'◯').join(' ');steps[0].classList.toggle('done',n>=3);steps[1].classList.toggle('done',n>=4);steps[2].classList.toggle('done',n>=5);panel.querySelector('.ocean-replay').hidden=!progress.complete;const goal=progress.target;const dir=panel.querySelector('.goal-direction');if(goal){const dy=goal.position[1]-position.y;dir.textContent=Math.abs(dy)>1.3?(dy>0?'↑':'↓'):'➤';dir.style.transform=Math.abs(dy)>1.3?'none':`rotate(${Math.atan2(goal.position[2]-position.z,goal.position[0]-position.x)+Math.atan2(camera.position.x-position.x,camera.position.z-position.z)}rad)`;dir.title=Math.abs(dy)>1.3?(dy>0?'Nổi lên':'Lặn xuống'):'Hướng tới điểm tiếp theo';}else{dir.textContent='★';dir.style.transform='none';}}
 panel.querySelector('.ocean-replay').onclick=()=>{progress.restart();celebrate=0;};
 return {get state(){return {index:progress.index,round:progress.round,complete:progress.complete,target:progress.target};},canEat(position){const g=OCEAN_GOALS[3];return progress.index===3&&Math.hypot(position.x-g.position[0],position.z-g.position[2])<3&&Math.abs(position.y-g.position[1])<1.3;},foodPosition:new T.Vector3(...OCEAN_GOALS[3].position),update(dt,position,boost=false,eating=false){time+=dt;if(progress.advance(position,eating)){chime();celebrate=1.2;}celebrate=Math.max(0,celebrate-dt);markers.forEach((g,i)=>{g.visible=i>=progress.index;const active=i===progress.index;g.children.forEach(m=>{m.material.opacity=active?.95:.22;m.material.emissiveIntensity=active?.65:.1;});if(i>=3)g.rotation.y+=dt*.6;g.scale.setScalar(active?1+Math.sin(time*3)*.035:1);});panel.classList.toggle('celebrate',celebrate>0);updatePanel(position);if(boost){spawn+=dt;while(spawn>.065){spawn-=.065;const particle=trail.find(p=>p.life<=0);if(particle){particle.life=.9;particle.mesh.visible=true;particle.mesh.position.copy(position).add(new T.Vector3((Math.random()-.5)*.6,1.5,0));}}}for(const p of trail)if(p.life>0){p.life-=dt;p.mesh.position.y+=dt*.5;p.mesh.material.opacity=Math.max(0,p.life);p.mesh.visible=p.life>0;}},dispose(){group.removeFromParent();geometries.forEach(g=>g.dispose());materials.forEach(m=>m.dispose());panel.remove();sound.remove();audio?.close().catch(()=>{});}};
}
